name: ⚓ Filter | Parse 🔰 
# This will likely increase as Repo Size gets bigger over time
#MAX_RUNTIME: 30-45 Mins
on:
  workflow_dispatch: # Whenever manually run from actions-tab
  schedule:
    #- cron: "45 23 * * *" #( 11:45 PM UTC --> 05:30 AM Morning )
    - cron: "59 * * * *" #( Every 59 Mins )
#------------------------------------------------------------------------------------#
jobs:
  Parse:
    runs-on: ubuntu-latest
    #timeout-minutes: 45 # Can't afford to finish the 2000 Minutes quotes    
    permissions:
      contents: write
      
    steps:        
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main  

      - name: Install Coreutils
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          sudo apt update -y
          sudo apt install coreutils curl dos2unix jq moreutils wget -y
          # Again just because
          sudo apt install coreutils curl dos2unix jq moreutils wget -y
        continue-on-error: true

      - name: Install eget
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          # eget for bins
          sudo wget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/eget" -O "/usr/local/bin/eget"
          sudo chmod +xwr "/usr/local/bin/eget"
        continue-on-error: false

      - name: Install Deps
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          #anew
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/anew" --to "/usr/local/bin/anew"
          #asn
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/asn" --to "/usr/local/bin/asn"
          #asnmap
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/asnmap" --to "/usr/local/bin/asnmap"
          #cut-cdn
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/cut-cdn" --to "/usr/local/bin/cut-cdn"          
          # dirstat-rs for tree
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/ds" --to "/usr/local/bin/ds"          
          #dnsx
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/dnsx" --to "/usr/local/bin/dnsx"
          #HTTPx
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/httpx" --to "/usr/local/bin/httpx"
          #inscope
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/inscope" --to "/usr/local/bin/inscope"
          #mapcidr
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/mapcidr" --to "/usr/local/bin/mapcidr"
          #ripgrep
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/ripgrep" --to "/usr/local/bin/ripgrep"
          #scopegen
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/scopegen" --to "/usr/local/bin/scopegen"
          #scopeview
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/scopeview" --to "/usr/local/bin/scopeview"
          #spk
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/spk" --to "/usr/local/bin/spk"
          #rclone
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/rclone" --to "/usr/local/bin/rclone"
          #yq
          sudo eget "https://raw.githubusercontent.com/Azathothas/Toolpacks/main/x86_64/yq" --to "/usr/local/bin/yq"
        continue-on-error: true

      - name: Get Data
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          #Latest --> 24 hr
          wget --quiet --show-progress --progress=bar "https://r2-pub.prashansa.com.np/certstream_domains_latest.txt" -O "/tmp/certstream_domains.txt"
          echo -e "\n[+] Total Domains (certstream_domains_latest.txt): $(wc -l < /tmp/certstream_domains.txt)\n"
          echo -e "[+] Total Size (certstream_domains_latest.txt): $(du -h /tmp/certstream_domains.txt | awk '{print $1}')\n"
          #Weekly --> 7-8 Days
          wget --quiet --show-progress --progress=bar "https://r2-pub.prashansa.com.np/certstream_domains_weekly.txt" -O "/tmp/certstream_domains_7days.txt"
          #Stats
          export SSL_7DAYS_TOTAL="$(wc -l < /tmp/certstream_domains_7days.txt)"
          echo "SSL_7DAYS_TOTAL=$SSL_7DAYS_TOTAL" >> $GITHUB_ENV
          echo -e "\n[+] Total Subs (certstream_domains_7days.txt): $SSL_7DAYS_TOTAL"
          echo -e "[+] Total Size (certstream_domains_7days.txt): $(du -h /tmp/certstream_domains_7days.txt | awk '{print $1}')\n"
        continue-on-error: true

      - name: Filter 🇧🇩 ccTLDs (Bangladesh)
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          mkdir -p "$GITHUB_WORKSPACE/main/Bangladesh"
          cd "$GITHUB_WORKSPACE/main/Data/Bangladesh"
          # Source : https://bdia.btcl.com.bd/
          #(ALL)
          #Last 24 Hr
          #.xn--54b7fta0cc --> .বাংলা
          grep -Ei '\.bd$|\.xn--54b7fta0cc$' "/tmp/certstream_domains.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Bangladesh/certstream_domains_bd_all_24h.txt"
          #Last 7 Days
          grep -Ei '\.bd$|\.xn--54b7fta0cc$' "/tmp/certstream_domains_7days.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Bangladesh/certstream_domains_bd_all_7days.txt"
          #README.md
          cd "$GITHUB_WORKSPACE/main"
          #cat INFO
          echo -e "\n" > "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo '---' >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo -e "- #### 🖨️ **Stats** \`24Hr\`⏲️ ➼ $(date +'%Y_%m_%d')" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo '```console' >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          #Total 
          echo -e "\n--> 🌐 Total" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ALL): +$(wc -l < /tmp/certstream_domains.txt)\n" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          #bd_ccTLDs
          echo -e "\n--> 🇧🇩 bd_ccTLDs" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ALL): +$(wc -l < $GITHUB_WORKSPACE/main/Bangladesh/certstream_domains_bd_all_24h.txt)" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo '```' >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          #7Days
          echo -e "- #### 🖨️ **Stats** \`7Days\`⏲️ ➼ $(date +'%Y_%m_%d') <--> $(date -d "7 days ago" +'%Y_%m_%d')" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo '```console' >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          #Total
          echo -e "\n--> 🌐 Total" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ALL): +${{ env.SSL_7DAYS_TOTAL }}\n" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          #bd_ccTLDs
          echo -e "\n--> 🇧🇩 bd_ccTLDs" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ALL): +$(wc -l < $GITHUB_WORKSPACE/main/Bangladesh/certstream_domains_bd_all_7days.txt)" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo '```' >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/Bangladesh/README.md"
        continue-on-error: true
        
      - name: Filter 🇷🇺 ccTLDs (Russia)
        run: |
          # Presets
          set -x ; set +e
          #--------------#
          mkdir -p "$GITHUB_WORKSPACE/main/Russia"
          cd "$GITHUB_WORKSPACE/main/Data/Russia"
          # Source : https://en.wikipedia.org/wiki/.ru
          #(ALL)
          #Last 24 Hr
          grep -Ei '\.ru$' "/tmp/certstream_domains.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Russia/certstream_domains_ru_all_24h.txt"
          #Last 7 Days
          grep -Ei '\.ru$' "/tmp/certstream_domains_7days.txt" | sort -u -o "$GITHUB_WORKSPACE/main/Russia/certstream_domains_ru_all_7days.txt"
          #README.md
          cd "$GITHUB_WORKSPACE/main"
          #cat INFO
          echo -e "\n" > "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo '---' >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo -e "- #### 🖨️ **Stats** \`24Hr\`⏲️ ➼ $(date +'%Y_%m_%d')" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo '```console' >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          #Total 
          echo -e "\n--> 🌐 Total" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ALL): +$(wc -l < /tmp/certstream_domains.txt)\n" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          #ru_ccTLDs
          echo -e "\n--> 🇷🇺 ru_ccTLDs" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ALL): +$(wc -l < $GITHUB_WORKSPACE/main/Russia/certstream_domains_ru_all_24h.txt)" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo '```' >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          #7Days
          echo -e "- #### 🖨️ **Stats** \`7Days\`⏲️ ➼ $(date +'%Y_%m_%d') <--> $(date -d "7 days ago" +'%Y_%m_%d')" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo '```console' >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          #Total
          echo -e "\n--> 🌐 Total" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ALL): +${{ env.SSL_7DAYS_TOTAL }}\n" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          #ru_ccTLDs
          echo -e "\n--> 🇷🇺 ru_ccTLDs" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo -e "[+] New/ReNewed SSL Certs (ALL): +$(wc -l < $GITHUB_WORKSPACE/main/Russia/certstream_domains_ru_all_7days.txt)" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo '```' >> "$GITHUB_WORKSPACE/main/Russia/README.md"
          echo -e "" >> "$GITHUB_WORKSPACE/main/Russia/README.md"
        continue-on-error: true
        
      - name: Get DateTime
        run: |
          # Date Time
          UTC_TIME=$(date +'%Y-%m-%d (%I:%M:%S %p)')
          echo "UTC_TIME=$UTC_TIME" >> $GITHUB_ENV
          
      - name: Git Pull
        run: |
           cd "$GITHUB_WORKSPACE/main" && git pull origin main
        continue-on-error: true
        
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./main
          commit_user_name: Azathothas # defaults to "github-actions[bot]"
          commit_user_email: AjamX101@gmail.com # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_message: "✅ ⚓ Filter | Parsed 🔰 CertStream Data 🌊 <-- ${{ env.NEPALI_TIME }} ⌚"
          #push_options: '--force'
